#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path(File.dirname(__FILE__))

gem "activesupport"
gem "railsgame"
require "railsgame"

# Example game files
require "example_room.rb"
require "example_player.rb"

RailsConfigDir = File.expand_path(File.join(File.dirname(__FILE__),
					    "..", "config"))
JuggernautHosts = File.join(RailsConfigDir, "juggernaut_hosts.yml")

server = RailsGame::Server.new
server.jug_hosts_file(JuggernautHosts)
server.connect

# Just prints whether connection was successful
if server.connected?
  print "GameServer: Connected!\n"
else
  print "GameServer: Not Connected!\n"
end

server.loop_while_connected

print "GameServer: exited\n"
